[build]
publish = "_site"
command = "./build-website.sh"

[[headers]]
  # All not latest documentation.
  for = "/docs/envoy/v*"
  [headers.values]
    # https://support.google.com/webmasters/answer/93710?hl=en
    # Do not index.
    X-Robots-Tag = "noindex"

[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "frame-ancestors 'self';"
